banco = str(input("BANCO: "))
agencia = str(input("AGÊNCIA: "))
numero = int(input("NUMERO DA CONTA: "))
titular = str(input("NOME DO TITULAR DA CONTA: "))
print("===== BEM VINDO AO {}, É UM PRAZER TER VOCÊ DE VOLTA!! =====".format(banco))
print("PARA PODER USAR NOSSOS SERVIÇOS, PRECISAMOS DE UM DEPOSITO INICIAL")
print("QUANTO IRA QUERER DEPOSITAR HOJE {}?".format(titular))
deposito1 = float(input("VALOR: R$"))
print("{}, DEPOSITOU R${:.2F}".format(titular, deposito1))
print("O QUE QUER FAZER AGORA:")
print("DEPOSITO - SAQUE - SAIR")
resp1 = str(input())
if resp1 == 'Deposito' or resp1 == 'DEPOSITO' or resp1 == 'deposito':
    print("QUAL O VALOR DO DEPOSITO?")
    deposito2 = float(input("VALOR: R$"))
    novoDeposito = (deposito1 + deposito2)
    print("{}, DEPOSITOU MAIS R${:.2F}, SALDO ATUALIZADO DA CONTA É DE R${:.2F}".format(titular, deposito2, novoDeposito))
    print("{}, VOCÊ ATINGIU O LIMITE MAXIMO DE DEPOSITOS POR DIA".format(titular))
    print("O QUE QUER FAZER AGORA:")
    print("SAQUE - SAIR")
    resp2 = str(input())
elif resp1 == 'Saque' or resp1 == 'SAQUE' or resp1 == 'saque':
    print("QUAL O VALOR QUE QUER SACAR HOJE {} ?".format(titular))
    saque = float(input("VALOR: R$"))
    saque1 = (deposito1 - saque)
    print("VOCÊ SACOU R${:.2F}, SALDO ATUALIZADO DA CONTA É DE R${:.2F}".format(saque, saque1))
    print("O QUE QUER FAZER AGORA:")
    print("DEPOSITO - SAQUE - SAIR")
    resp2 = str(input())
elif resp1 == 'Sair' or resp1 == 'SAIR' or resp1 == 'sair':
    print("===== OBRIGADO POR UTILIZAR NOSSOS SERVIÇOS {}, {} AGRADEÇE SUA VISITA =====".format(titular, banco))
if resp2 == 'Saque' or resp2 == 'SAQUE' or resp2 == 'saque':
    print("QUAL O VALOR QUE QUER SACAR HOJE {} ?".format(titular))
    saque = float(input("VALOR: R$"))
    saque1 = (novoDeposito - saque)
    print("VOCÊ SACOU R${:.2F}, SALDO ATUALIZADO DA CONTA É DE R${:.2F}".format(saque, saque1))
elif resp2 == 'Sair' or resp2 == 'SAIR' or resp2 == 'sair':
    print("===== OBRIGADO POR UTILIZAR NOSSOS SERVIÇOS {}, {} AGRADEÇE SUA VISITA =====".format(titular, banco))

